### ISSUE TITLE
List of powned entries ?

### ISSUE THREAD

**Issue by olivierSOW** [kapsiR/HaveIBeenPwnedKeePassPlugin#10]
Hi,

I just find your plugin. I have get already more than 200 entries in my Keepass DB. I launch a check on all entries which report 41 entries powned. How can i know which ones is powned ? Can you report the list ?

Thanx

**Comment by olivierSOW** [comment]
I just found in your source code that you add a "pwned" tag in entry which is pwned :/

**Comment by kapsiR** [comment]
@olivierSOW Yes. In the readme is a screenshot how you can filter by that tag 😉

https://github.com/kapsiR/HaveIBeenPwnedKeePassPlugin/blob/main/images/showAllPwned.jpg
