### ISSUE TITLE
Question - Install under ubuntu

### ISSUE THREAD

**Issue by yuriw** [kapsiR/HaveIBeenPwnedKeePassPlugin#6]
Can this plugin be installed not on Windows but on Linux(ubunut) instance of keepass2 ?

Thx

**Comment by alexrashed** [comment]
Yes, I'm using it on Ubuntu (with mono).

**Comment by kapsiR** [comment]
As already answered by @alexrashed, it's possible yes. 

I'll keep this issue open to add some clarification to the readme or a faq section... 

I think I'll have some time today at night to add that. 😉

**Comment by yuriw** [comment]
@alexrashed I used to use it with mono, but keepass2 now seems to be available from native ubuntu repos via `apt install keepass2`.  That's what prompted my question.
How to install it on ubuntu ?  Where 
```
which keepass2 
/usr/bin/keepass2
```

**Comment by kapsiR** [comment]
Yes, KeePass is in the universe repos, but as you can [see here](https://packages.ubuntu.com/search?keywords=keepass2) with a dependency on libmono. 

As of my knowledge there is no plan right now to port it to .NET Core for "true native support".

**Comment by alexrashed** [comment]
> @alexrashed @kapsiR I used to use it with mono, but keepass2 now seems to be available from native ubuntu repos via `apt install keepass2`. That's what prompted my question.
> How to install it on ubuntu ? Where
> 
> ```
> which keepass2 
> /usr/bin/keepass2
> ```
> 
> any details appreciated !

I additionally installed mono-complete, but that was necessary for another plugin (so I can't say you need it). The default folder for the plugins with the package from the universe repo is `/usr/lib/keepass2/Plugins/`. Just copy the dll there, adjust the owner and restart Keepass. :)

**Comment by yuriw** [comment]
@alexrashed that helps, thx !

I see now:

![image](https://user-images.githubusercontent.com/3876474/80313412-99e9af00-879f-11ea-84d6-c6a229480142.png)

Will see if there is a better version...

**Comment by kapsiR** [comment]
Perfect. Thanks guys, will add that info today (night)

**Comment by yuriw** [comment]
@kapsiR but I am not sure, but something seems odd...
When I do `Check all passwords` I get:

![image](https://user-images.githubusercontent.com/3876474/80316536-48e3b600-87b3-11ea-9161-b47dc6abb932.png)

But when I do `Check current passwords` I actually see nothing?

Am I missing something ?

**Comment by kapsiR** [comment]
@yuriw You only get any alert, when an entry has been pwned.

Usually you don't have to check one single password manually, it's always checked automatically when you create/change one. (by default, can be disabled)

Feel free to open another issue if you have any ideas or if you'd like to see improvements in special cases.
