### ISSUE TITLE
`Check current password` functionality improvement request 

### ISSUE THREAD

**Issue by yuriw** [kapsiR/HaveIBeenPwnedKeePassPlugin#7]
When I do `Check all passwords` I get:

![image](https://user-images.githubusercontent.com/3876474/80316536-48e3b600-87b3-11ea-9161-b47dc6abb932.png)

But when I do `Check current password` I actually see nothing?
Ref: https://github.com/kapsiR/HaveIBeenPwnedKeePassPlugin/issues/6#issuecomment-619609467

I think `Check current password` should behave like https://haveibeenpwned.com/Passwords
For example, if a user wants to verify password `12345`, the website comes back with message:
![image](https://user-images.githubusercontent.com/3876474/80319233-489fe680-87c4-11ea-8250-ec7aaee3157a.png)

I suspect that novice users won't even know what the plugin does without such functionality.

**Comment by kapsiR** [comment]
Just to clarify, when you check a single entry, you only get a message, if the entry has been pwned.
From the readme `Check the current selected entry`:
![check single entry](https://raw.githubusercontent.com/kapsiR/HaveIBeenPwnedKeePassPlugin/master/images/checkSingleResult.jpg)



So is your intention that you always get a message, even if the password is ok?

**Comment by yuriw** [comment]
@kapsiR Yes I think when a single entry id checked in any case a message should be shown

**Comment by kapsiR** [comment]
Thanks for clarification. I'll consider it for the next release 😉

**Comment by kapsiR** [comment]
@yuriw You can try it out directly with the current [v0.6.0-preview](https://github.com/kapsiR/HaveIBeenPwnedKeePassPlugin/releases/tag/v0.6.0-preview) version 😉

**Comment by yuriw** [comment]
@kapsiR works great thx for quick implementation!
