### ISSUE TITLE
Ignore entry

### ISSUE THREAD

**Issue by fan2404** [kapsiR/HaveIBeenPwnedKeePassPlugin#8]
Hi, it would be nice to tag an entry or something to exclude it from checking. The condition could be extended similiar to ignoring expired entries.
1.

    private const string IgnoreTag = "ignore-pwned";
2.

    if (!pwEntry.Tags.Contains(IgnoreTag)) {
        // ...
    }
3.

    entries = entries.Where(entry => !entry.contains(IgnoreTag));

**Comment by kapsiR** [comment]
Will consider this for the next release, but can you clarifiy your use case please?

**Comment by fan2404** [comment]
Sure: I do have entries that are unavoidably pwned like a 4-digit pin code. These "passwords" do not qualify for a HIBP check as they are meant to be generic. With a few lines of code it would be possible to mark these entries for exclusion so they are not reported as breached.

**Comment by kapsiR** [comment]
So you don't even want to know whether these entries are pwned or in other words, they shouldn't be in the numbers? 

Do you want to tag them already in the first place or after the first time they got reported? (With a new tag, we've both options of course)  

I'm just thinking about a more generic approach with no need for manual actions but I'm afraid there is none...

**Comment by fan2404** [comment]
Yes.
I don't think this is possible without manual actions. That's why I thought of a tag to add by hand.

**Comment by kapsiR** [comment]
@fan2404 I have just released a [new preview](https://github.com/kapsiR/HaveIBeenPwnedKeePassPlugin/releases/tag/v0.6.0-preview2) version that you can use right now 😉

**Comment by fan2404** [comment]
Awesome, the toggle menu item makes it even more comfortable to use. gj
